
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "brickwalker",
    "name": "Artem Nedostup",
    "password": "1a2b3c4d"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "alpish",
    "name": "Sasha P",
    "password": "4a3b2c1d"
}