POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "brickwalker",
    "password": "1a2b3c4d"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "alpish",
    "password": "wrongpassword"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "alpish",
    "password": "4a3b2c1d"
}