PUT http://localhost:3003/api/blogs/61bb880efcf9d3ac14d12232
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyaWNrd2Fsa2VyIiwiaWQiOiI2MWJiMzZhMjY3YzhhYTMxNDhlMzRmN2EiLCJpYXQiOjE2Mzk2NzkzMDgsImV4cCI6MTYzOTY4MjkwOH0.RlZR5ceYvlfSL6iBaAtzLQ6dP1DMJNpiffytpYbhb0o

{
    "title": "Kari4"
}

###
PUT http://localhost:3003/api/blogs/61bb880efcf9d3ac14d12232
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFscGlzaCIsImlkIjoiNjFiYjM3MjEwZDFlOWVjZWQxYTljYzEzIiwiaWF0IjoxNjM5Njc5NDE5LCJleHAiOjE2Mzk2ODMwMTl9.qqanOI_8Pdibg8g9UZHasGzRGz9IinOC2BxRlqEYXTU

{
    "title": "Kari4"
}

###
PUT http://localhost:3003/api/blogs/61bb880efcf9d3ac14d12232
Content-Type: application/json

{
    "title": "Kari4"
}
